# 3 endpointes, 2 different users: user, user2

### First statement
GET {{host}}/{{user2}}/assistant?question="my name is SnoopDog2!"

> {%
    client.test("Status", function () {
        client.assert(response.status === 200, "Unexpected response status");
    });
%}

### First question
GET {{host}}/{{user2}}/assistant?question="do you have any neurotic dogs?"

> {%
    client.test("Status", function () {
        client.assert(response.status === 200, "Unexpected response status");
    });
%}

### Followup question
GET {{host}}/{{user}}/assistant?question="fantastic. when can i schedule an appointment to pickup Prancer from the New York City location?"

> {%
    client.test("Status", function () {
        client.assert(response.status === 200, "Unexpected response status");
    });
%}

### Fetch messages
GET {{host}}/{{user2}}/messages

> {%
    client.test("Status", function () {
        client.assert(response.status === 200, "Unexpected response status");
    });
%}

### Clear messages
DELETE {{host}}/{{user2}}/messages/clear

> {%
    client.test("Status", function () {
        client.assert(response.status === 204, "Unexpected response status");
    });
%}


### Info
GET {{host}}/actuator/info

### Check operations
GET {{host}}/actuator/metrics/gen_ai.client.operation

### Check token usage
GET {{host}}/actuator/metrics/gen_ai.client.token.usage

### Health
GET {{host}}/actuator/health

### Liveness
GET {{host}}/actuator/health/liveness

### Readiness
GET {{host}}/actuator/health/readiness
